name: Django CI

on:
  push:
    branches: [ "workflows-test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:

      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./bargainbuddy/requirements.txt
    - name: Run Tests
      run: |
        python ./bargainbuddy/manage.py test